#!/bin/bash
echo -e "\n====== Installing zsh ======\n"


sudo apt install -y zsh util-linux-user wget &&
chsh -s /usr/bin/zsh root &&
echo $SHELL

if [ -z "$(ls -A $HOME/.oh-my-zsh)" ]; then
    echo "getting oh-my-zsh"
    wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
fi


ln -svf ~/dotfiles/.zshrc ~/.zshrc

ln -svf ~/dotfiles/config/.dircolors ~/.dircolors
eval $(dircolors ~/.dircolors)

echo "WRITE: "
echo "source ~/.zshrc"