#!/bin/bash

git checkout main
git pull origin main

git checkout -b merge-dev-to-main

git checkout dev
git pull origin dev

git checkout merge-dev-to-main

git merge dev

echo "Created branch 'merge-dev-to-main' from main and merged dev into it"
