#!/bin/bash 

if ( isredhat ); then 
    sudo ln -s -v /etc/httpd/sites-available/$1 /etc/httpd/sites-enabled/$1
else
    sudo ln -s -v /etc/apache2/sites-available/$1 /etc/apache2/sites-enabled/$1
fi
