#!/bin/bash

if [ $# == 1 ]; then
   sudo a2dissite $1 >> /dev/null && echo "site disabled"
   sudo a2ensite $1 >> /dev/null && echo "site enabled"
fi

sudo service apache2 restart

echo "apache restarted"