#!/bin/bash

if [ $# == 1 ]; then
   sudo a2dissite $1 >> /dev/null && echo "site disabled"
   sudo a2ensite $1 >> /dev/null && echo "site enabled"
fi

if ( isredhat ) 
then
   sudo systemctl restart httpd.service 
else
   sudo service apache2 restart
fi

echo "apache restarted"