#!/bin/bash

if [ $# -eq 0 ]; then
   echo "Please provide input file as argument"
   exit 1
fi

input_file=$1

old_url="http://localhost:10049"
new_url="https://orangered-jackal-589322.hostingersite.com"

output_file="${input_file%.*}-out.${input_file##*.}"

sed "s|$old_url|$new_url|g" "$input_file" > "$output_file"