#!/usr/bin/env bash

upload_max_filesize=240M
post_max_size=50M
max_execution_time=100
max_input_time=223

for key in upload_max_filesize post_max_size max_execution_time max_input_time
do
 sudo sed -i "s/^\($key\).*/\1 $(eval echo = \${$key})/" /etc/php/7.4/cli/php.ini
 sudo sed -i "s/^\($key\).*/\1 $(eval echo = \${$key})/" /etc/php/7.4/apache2/php.ini 
done

echo "New values:"
echo "- upload_max_filesize=$upload_max_filesize
- post_max_size=$post_max_size
- max_execution_time=$max_execution_time
- max_input_time=$max_input_time"

sudo service apache2 restart

echo ""
echo "apache restarted"