#!/bin/bash

# Update Package Index
sudo apt update

# Enable PHP PPA
sudo add-apt-repository ppa:ondrej/php 

# Install Apache2, MySQL, PHP
sudo apt install -y apache2 mysql-server php8.0 php8.0-mysql libapache2-mod-php8.0 php8.0-cli 

# Allow to run Apache on boot up
sudo systemctl enable apache2

# Restart Apache Web Server
sudo systemctl start apache2

# Adjust Firewall
sudo ufw allow in "Apache Full"

# Allow Read/Write for Owner
sudo chmod -R 0755 /var/www/html/

# Create info.php for testing php processing
sudo echo "<?php phpinfo(); ?>" > /var/www/html/info.php

# Open localhost in the default browser
# xdg-open "http://localhost"
# xdg-open "http://localhost/info.php"

# install some php extensions
sudo apt install -y php8.0-mbstring php8.0-curl php8.0-dom php8.0-gd php8.0-xml php8.0-zip php8.0-gettext php8.0-xdebug
# sudo apt install phpmyadmin

sudo a2enmod rewrite

a2res



