#!/bin/bash

echo "starting setup"

log_file=~/install_progress_log.txt

function install-package {

        sudo apt install -y $1

        if type -p $1 > /dev/null; then
                echo "$1 Installed" >> $log_file
        else
                echo "$1 FAILED TO INSTALL!!!" >> $log_file
        fi
}

function install-snap {
        sudo snap install --classic $1
        if type -p $1 > /dev/null; then
                echo "$1 Installed" >> $log_file
        else
                echo "$1 FAILED TO INSTALL!!!" >> $log_file
        fi
}


function install-brave {

        curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add - &&
        echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list &&
        sudo apt update &&
        install-package brave-browser
}       

function install-code {
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
        rm -f packages.microsoft.gpg

        sudo apt install apt-transport-https
        sudo apt update
        install-package code # or code-insiders
}


# command line programs
install-package curl
install-package unzip
install-package vim
install-package git
install-package nodejs
install-package npm
install-package lolcat
install-package neofetch

# graphical programs
install-package gnome-tweaks
install-package filezilla
install-package calibre
install-package gimp

# needs special treatment
install-brave
install-code


#==============
# Give the user a summary of what has been installed
#==============
echo -e "\n====== Summary ======\n"
cat $log_file
echo
rm $log_file
