#!/bin/bash

echo "starting setup"

log_file=~/install_progress_log.txt

function install-package {

        if ( isredhat ); then
                sudo dnf install -y $1
        else
                sudo apt install -y $1
        fi

        if type -p $1 > /dev/null; then
                echo "$1 Installed" >> $log_file
        else
                echo "$1 FAILED TO INSTALL!!!" >> $log_file
        fi
}

function install-snap {
        sudo snap install --classic $1
        if type -p $1 > /dev/null; then
                echo "$1 Installed" >> $log_file
        else
                echo "$1 FAILED TO INSTALL!!!" >> $log_file
        fi
}


function install-brave {

        if ( isredhat ); then
                sudo dnf install -y dnf-plugins-core &&
                sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/ &&
                sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc &&
                sudo dnf install -y brave-browser
        else
                curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add - &&
                echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list &&
                sudo apt update &&
                install-package brave-browser
        fi
}       

function install-code {
        if ( isredhat ); then
                sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
                sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
                sudo dnf check-update
                sudo dnf install -y code
        else
                install-snap code
        fi
}

# command line programs
install-package curl
install-package unzip
install-package vim
install-package git
install-package nodejs
install-package npm
install-package lolcat
install-package neofetch

# graphical programs
install-package gnome-tweaks
install-package filezilla
install-package calibre
install-package gimp

# needs special treatment
install-brave
# install-code


#==============
# Give the user a summary of what has been installed
#==============
echo -e "\n====== Summary ======\n"
cat $log_file
echo
rm $log_file
