#!/usr/bin/env bash

upload_max_filesize=240M
post_max_size=50M
max_execution_time=0
max_input_time=223

if ( isdebian )
then
    php_ini_file=/etc/php/7.4/apache2/php.ini
else
    php_ini_file=/etc/php.ini
fi

for key in upload_max_filesize post_max_size max_execution_time max_input_time
do
 sudo sed -i "s/^\($key\).*/\1 $(eval echo = \${$key})/" $php_ini_file
done

echo "New values:"
echo "- upload_max_filesize=$upload_max_filesize
- post_max_size=$post_max_size
- max_execution_time=$max_execution_time --unlimited
- max_input_time=$max_input_time"

# restart apache
a2res