#!/bin/bash

# Find the only folder inside ~/domains
DOMAIN_DIR=$(find "$HOME/domains" -mindepth 1 -maxdepth 1 -type d | head -n 1)

# Find the only theme folder inside public_html/wp-content/themes
THEME_DIR=$(find "$DOMAIN_DIR/public_html/wp-content/themes" -mindepth 1 -maxdepth 1 -type d | head -n 1)

# Change into that directory
cd "$THEME_DIR" || exit

# Print where we landed
pwd