#!/bin/bash

function start {
    echo -e "*** Starting wpstart script ***"
    ask_for_data $@
    create_db
    install
    change_permissions
    config
}

function ask_for_data {

    PROJECT_NAME=$1

    # Site
    URL=$PROJECT_NAME".local"
    TITLE=$PROJECT_NAME
    ADMIN_USER=""
    ADMIN_PASS=""
    ADMIN_EMAIL="man.lukosevicius@gmail.com"

    # Database
    DB_NAME=$PROJECT_NAME
    DB_USER=""
    DB_PASS=""

    # Ask to enter command if not passed with arguments   
    if [ $# == 0 ]; then
        echo $#
        echo "Please provide project name"
        exit 
    fi

    PEOJECT_NAME=$1

    echo "Project name: $PROJECT_NAME"
    echo "Site URL: $URL"
}

function ask_questions {
    echo "so..."
}

function check_for_config {

    # wpstart_config should just have 4 lines with these values:
    # db user
    # db password
    # wp admin user
    # wp admin password

    if [ ! -f /home/mantas/dotfiles/config/wpstart_config ]; then
        echo "wpstart_config file not found"
        exit 0
    fi

    count=0
    while IFS= read -r line; do
        first_letter=${line:0:1}
        if [ $first_letter != '#' ]
        then
            if [ $count == 0 ]
            then
                DB_USER=$line
            elif [ $count == 1 ]
            then
                DB_PASS=$line
            elif [ $count == 2 ]
            then
                ADMIN_USER=$line
                echo "Admin user: $ADMIN_USER"
            elif [ $count == 3 ]
            then
                ADMIN_PASS=$line
                echo "Admin password: $ADMIN_PASS"
            fi
            count=$((count+1))
        fi
    done < /home/mantas/dotfiles/config/wpstart_config
}


function create_db {
    sudo mysql -e "DROP DATABASE IF EXISTS "$DB_NAME &&
    sudo mysql -e "CREATE DATABASE "$DB_NAME && 
    echo "Created database \""$DB_NAME"\""
}

function install {
    wp core download &&
    wp config create --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASS &&
    wp core install --url=$URL --title=$TITLE --admin_user=$ADMIN_USER --admin_password=$ADMIN_PASS --admin_email=$ADMIN_EMAIL
}

function change_permissions {
    PERMISSIONS=777
    sudo chmod -R $PERMISSIONS *
    echo "Change all files permissions to $PERMISSIONS"
}

function config {
    wp config set 'FS_METHOD' 'direct' --add
    wp config set 'WP_DEBUG' 'true' --add
}

start $@