#!/bin/bash

if [ $# == 1 ]; then
   sudo a2dissite $1 >> /dev/null && echo "site disabled"
   sudo a2ensite $1 >> /dev/null && echo "site enabled"
fi
sudo systemctl restart httpd.service &&
echo "apache restarted"