#!/bin/bash

chosen_editor=code 

if ! code -v COMMAND &> /dev/null
then
    chosen_editor=vim
fi

# if [ -z "$2" ]; then
#     if [ -x "$(command -v $primary_editor)" ]; then
      # chosen_editor=$primary_editor
#     else
#       chosen_editor="sudo vim"
#     fi
# else
#   if [ $2 == "v" ]; then  
#       chosen_editor="sudo vim"
#   elif [ $2 == "c" ]; then
#       chosen_editor="code"
#   fi
# fi

case $1 in
  "main") file_path=~/dotfiles/alias/.main ;;
  "nav") file_path=~/dotfiles/alias/.navigation ;;
  "tmp") file_path=~/dotfiles/alias/.tmp ;;
  "navigation") file_path=~/dotfiles/alias/.navigation ;;
  "functions") file_path=~/dotfiles/alias/.functions ;;
  "zsh") file_path=~/dotfiles/.zshrc ;;
  "bash") file_path=~/.bashrc ;;
  "profile") file_path=~/dotfiles/.bash_profile ;;
  "hosts") file_path=~/etc/hosts ;;
  "script") file_path=~/dotfiles/scripts/$2 ;;
  "katilai") file_path=/var/www/katilai-scrapers/katilai_scrapers/spiders/config.json ;;
  *) echo "no such option"; exit 0;;
esac

echo $file_path

if [ -n "$1" ];
  then
    $chosen_editor $file_path
fi