#!/bin/bash

fbi_count=0
while true
do 
    if nmcli d wifi list | grep FBI-surveillance
    then
        echo "connection found" 
        break
    else
        echo -ne "scanning... ($fbi_count) \r";
        fbi_count=$(($fbi_count+1))
    fi
    sleep 2
done

nmcli c up FBI-surveillance &&
echo "connected to FBI-surveillance"