#!/bin/bash

# if [ ! -f .env ];
#     then
#         echo ".env not found"
#         exit
# fi

# # DB_NAME=`grep -oP "(?<=DB_NAME=').*(?=')" .env`

# if [ -z "$DB_NAME" ];
#     then
#         echo "Couldn't find database name in .env file"
#         exit
# fi

DB_NAME="test"


echo "dumping database: "$DB_NAME

TIME=`date "+%y-%m-%d_%H-%M"`
EXPORT_FILE_NAME=$DB_NAME'-'$TIME'.sql'

mkdir -p sql
rm 'sql/'$DB_NAME'-'*

sudo mysqldump $DB_NAME > 'sql/'$EXPORT_FILE_NAME &&
echo "exported $EXPORT_FILE_NAME"
