#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Enter commit message"
    exit
fi

if [ ! -d .git ]; then
    echo "not a git directory"
    exit
fi

wpdump &&
git add . &&
git commit -m "$1" &&
git push origin master
